### ISSUE TITLE
Thanks for your bewisclient

### ISSUE THREAD

**Issue by mcdodge34** [Bewis09/bewisclient#1]
Didn't find a better way to contact you, I admire your work, this mod is exactly what I needed, it replace most of the old IngameInfoXML I was missing. I had a little bit of a problem trying to run it on snapshot 23w13a (due to some mods we use, we're stuck with this version and can't upgrade to the pre-release.) I just edited the fabric-mod.json inside your 1.1-1.9.4-fabric to make it work on the 23w13a version I use, it seems to work without any issues

Here's the changes I did to the fabric-mod.json, simple edit
 "depends": {
    "fabricloader": ">=0.14.11",
    "fabric-api": "*",
    "minecraft": ">=1.19.3", instead of ­tilde (sorry can't type it on my keyboard layout)1.19.3
    "java": ">=17"

If there's a link or way to send you a small donation via paypal or other donation methods, I would be glad to send you 5$ CAD whatever it can be worth in your Country.

I really hope you'll notice this message, I didn't find any other ways of contacting you.

**Comment by Bewis09** [comment]
Hi, thank you for your feedback! It's cool that you could fix it yourself and it worked. I don't need your money, but thank you for your offer. Buy some chips or a bar of chocolate 😊. If you find any issues with the mod, please message me.

Have fun with Bewisclient
