### ISSUE TITLE
Crash at Macro Screen

### ISSUE THREAD

**Issue by ItsukaHiro** [Bewis09/bewisclient#2]
I try to add macro in macro screen, but it's crash immediately when clicking to [Add] button.

**Comment by Bewis09** [comment]
can you send the crash report?

**Comment by Bewis09** [comment]
okay, I found this bug myself and now trying to fix it

**Comment by Bewis09** [comment]
Okay, I fixed it, releasing hotfix update now. It was a caused by the use of List.of() and not new ArrayList<>()
