### ISSUE TITLE
Disable Cinematic Zoom & Add instant zoom

### ISSUE THREAD

**Issue by ItsukaHiro** [Bewis09/bewisclient#3]
Maybe I'm the only one. but can you add a way to disable (or just remove) cinematic zoom? It's really annoying when using zoom and aiming, or just move around to see everything with slow motion camera.

Another thing about zooming is zoom animation. I know is a plus-point when the mod have this, but can we have a option to fully disable animation ? It's will much more convienent (sorry about grammar) in some fast-move occasion.

**Comment by Bewis09** [comment]
I can add it in the next big version (1.3) in around two weeks. I will not add it sooner, because I release updates at a very high frequency
